[package]
name = "rust-releases-io"
version = "0.15.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
http_client = ["attohttpc"]

# NB: excluded from SemVer, please do not use this in your crates
internal_dl_test = []

[dependencies]
thiserror = "1.0.24"

directories-next = "2.0.0"

# feature: http_client
attohttpc = { version = "0.17.0", optional = true }


