status = [
    "test (stable)",
    "test (beta)",
    "test (nightly)",
    "test (macos)",
    "test (win-gnu)",
    "test (win-msvc)",
    "rustfmt",
    "clippy",
    "cargo_deny (advisories)",
    "cargo_deny (bans licenses sources)",

    "msrv",
    "msrv-workspace-crates (crates/rust-releases-channel-manifests)",
    "msrv-workspace-crates (crates/rust-releases-core)",
    "msrv-workspace-crates (crates/rust-releases-io)",
    "msrv-workspace-crates (crates/rust-releases-rust-changelog)",
    "msrv-workspace-crates (crates/rust-releases-rust-dist)",
    "msrv-workspace-crates (crates/rust-releases-rust-dist-with-cli)",
]

delete_merged_branches = true