[licenses]
unlicensed = "deny"
copyleft = "deny"
confidence-threshold = 0.925
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "MPL-2.0",
    "Unlicense",
    "Zlib",
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"

ignore = [
    # `stdweb` is unmaintained; This doesn't mean it's broken, but if possible, we should look for a replacement.
    # Currently a replacement is not really available as it is a dependency of rusoto, which we use to
    # connect to AWS S3. AWS recently has been recruiting many Rust developers so maybe there will also be an official
    # AWS Rust SDK in the future?
    "RUSTSEC-2020-0056"
]