[package]
name = "rust-releases-core"
version = "0.15.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"
semver = "0.11.0"

[dev-dependencies]
yare = "1.0.1"
