[package]
name = "rust-releases-rust-dist"
version = "0.15.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-releases-core = { version = "0.15.0", path = "../rust-releases-core" }
rust-releases-io = { version = "0.15.0", path = "../rust-releases-io" }

thiserror = "1.0.24"

lazy_static = "1.4.0"
rusoto_core = { version = "0.46.0" }
rusoto_s3 = { version = "0.46.0" }
regex = "1.4.5"
tokio = { version = "1" }
